export const gpname = "NO 4 HARSURA GRAM PANCHAYAT";
export const gpaddress = "Vill-Suhari, PO-Rampur, PS-Tapan";
export const nameinprodhan = "No 4 Harsura Gram Panchayat";
export const gpcode = "HRGP";
export const gpnameinshort = "Harsura";
export const blockname= "Tapan Dev."
export const gpshortname= "Harsura"
export const gpmail=""
export const gptannumber=""