import { blockname, gpnameinshort } from "./gpinfor";

export const tendertermcon = [
  {
    eligible: [
      "The prospective bidders shall have satisfactorily completed as a prime agency during the last 3 (Three) years prior to the date of issue of this Notice at least one work of similar nature and having 60% (Sixty percent) (as per PWD and P&RD norms) of the estimated amount put to tender. Such work should be executed in the Government Sector, Zilla Parishad, Panchayat Samity, Gram Panchayat or Public Sector undertaking. Please note that Credential means Payment certificate (where NIT No., Memo. No., Fund, Name of Work, Work Order Memo. No., M.B.No., Page No., Bill amounts including necessary deductions, Voucher No.& date, PAN, GST Regn. No. etc. to be furnished clearly) which will be tagged with Work Order & Completion Certificate. A credential will not be used for more than one work i.e. multi-use of a single credential will not be allowed otherwise the tender may be treated as cancel.",
      `Photo copies of valid Pan Card, Valid 15-digit Goods and Services Tax registration Number (GSTIN) and up-to-date GST return under GST Act, 2017 must be uploaded in the appropriate folder. In case of Registered Engineering Co-Operative Societies and Registered Labour Co-Operative Societies, they are required to furnish valid Bye Law, Current Audit Report, Valid Clearance Certificate from A.R.C.S. for the year 2024-25 along with other relevant supporting documents. Authorized persons should sign the tender documents along with technical Bid documents. During scrutiny of Technical Bid/ Tender documents, if it is found that any information is incorrect, the technical bid /tender documents will be rejected without assigning any reason thereof. The Artho-O-Parikalpana Upo-samiti of ${gpnameinshort} Gram Panchayat office will have the sole discretion to decide the eligibility of the Contractor on the basis of his submitted documents and evaluation, and also reserves the right to refuse any explanation to the Contractor without assigning any reason thereof. The decision of the ${gpnameinshort} Gram Panchayat office authority will be final in this respect.`,
      "Intending bidders have to submit their bid online through the e-procurement (two cover systems) portal of http://www.wbtenders.gov.in. The scanned copy of the Tender Fee/Participation charge and earnest money is to be uploaded in the appropriate folder. The hard copy of the Tender Fee/Participation charge and EMD challan is to be deposited after opening of the Technical bid to the Office of the undersigned. The necessary Earnest Money and Tender Fee/Participation charge will be deposited by the bidder electronically (as per order no. 3975-F(Y) dtd.28.07.2016 & Memorandum No.2365-F(Y) dtd. 12.04.2018 of Finance Department, Govt. of West Bengal) online through their net banking-enabled bank account, maintained at any bank. Intending bidders will get the Beneficiary details from the e-tender portal with the help of a Digital Signature Certificate and may transfer the EMD from their respective Bank as per the Beneficiary name, Account No., Amount, Beneficiary Bank name (ICICI Bank), IFSC Code, and e-Proc Ref No. Intending bidders who want to transfer EMD through NEFT/RTGS must read the instruction of the Challan generated from the E_Procurement site. Bidders are also advised to submit the EMD of their bid at least 3 working days before the submission closing date as it requires time for processing the Payment of EMD & Tender Fee/Participation charge.",
      "The L1 bidder will have to show or submit original testimonials as the case may be after the opening of the Technical Bid.",
      "Bids from joint ventures are not allowed.",
      "Where an individual person holds a digital certificate in his own name duly issued to him against the company or the firm of which he happens to be a director or partner, such an individual person shall, while uploading any tender for and on behalf of such a company or firm, invariably upload a copy of the registered power of attorney showing clear authorization in his favour, by the rest of the directors of such company or the partners of such firm, to upload such tender. The power of attorney shall have to be registered in accordance with the provisions of the Registration Act, 1908.",
      "If for any reason the lowest tender is not accepted, a necessary decision shall be made by the Artho-O-Parikalpana Upo-Samiti regarding the finalization of the tender.",
      `The authority of ${gpnameinshort} GP reserves the right of accepting or rejecting any or all the Tenders and can distribute a part or the whole of the work(s) to any or among more than one participating Tenderers without assigning any reason. The said authority will not be bound to accept the lowest tender & if found submitting above 10% less of the work value, then the tenderer must have to submit rate analysis in a proper way.`,
      "Bids shall remain valid for a period not less than 120 days from the last date of submission of Financial Bid/Sealed Bid. If the bidder withdraws the bid during the period of bid validity, the earnest money as deposited will be forfeited forthwith without assigning any reason thereof.",
      "The intending bidders should know the fact that the rates in the BOQs are inclusive of all duties, taxes, royalties, cess, [including 1% L.W. Cess under W.B. Building and other Construction Workers (Regulation of Employments & Condition of Service) Act, 1996], toll taxes, and other levies payable by the Contractor under the Contract to the State / Central Government for any other cause, shall be included in the rates, prices, and total Bid price submitted by the bidder. 1% Cess under W.B. Building and other Construction Workers (Regulation of Employments & Condition of Service) Welfare Cess Act, 1996 will be deducted from the bills. No separate claim under any circumstances will be allowed.",
      "In this tender no arbitration will be allowed.",
      "No credential will be considered unless it is supported by Payment certificate, Work Order & Completion Certificate issued by the competent authority not below the rank of the Executive Engineer / Secretary / Executive Officer/BDO/ Pradhan of Gram Panchayat/ Chairman of Municipality as the case may be under whom the work has been executed ",
      "If any tenderer fails to produce the original hard copies or any other documents on demand of the tendering authority within a specified time frame or if any deviation is detected in the hard copies from the uploaded soft copies or if there is any suppression of fact, necessary penal action will be taken against the bidder as per rules.",
      "The Tenderers are advised to submit only required documents as prescribed in this notice. If it is found unnecessary documents submitted which has no connection related to this notice, his/her tender at Technical Bid stage may be cancelled without any intimation to him/her.",
      "No Mobilization / Secured advance will be allowed to selected agency.",
      "The bidders at their own responsibility and risk is encouraged to visit and examine the site of works and its surrounding and obtain all information that may be necessary for preparing the bid and entering into a contract for the work mentioned in the Notice. The cost of visiting the site shall be at the bidder’s own expense.",
      "Additional performance security @ 10% of the tendered amount shall be deposited when the bid rate is 80 % i.e. 20 % or above less (As per Finance Department, Audit Branch, Memorandum No. 4608-F(Y), Dated, 18th July, 2018).",
      "The additional performance Security shall be submitted in the form of Bank Guarantee from any scheduled bank before issuance of the Work Order. If the bidder fails to submit the additional performance security within seven working days from the date of issuance of letter of acceptance, his Earnest Money will be forfeited and other necessary actions as per NIT like blacklisting of the contractor etc, may be taken. The bank Guarantee shall have to be valid up to end of the contract period and shall be renewed accordingly, if required.",
      "The Bank Guarantee shall be returned immediately on successful completion of the contract. If the bidder fails to complete the work successfully, the additional performance security shall be forfeited at any time during the pendency of the contract period after serving proper notice to the contractor. Necessary provisions regarding deduction of security deposit from the progressive bills of the contractor as per relevant clauses of the contract shall in no way be altered/affected by provision of this additional performance security.",
      "In case of power of attorney empowering the power holder (Registered) to act as agency, agreement will be done only with the original agency and such power of attorney will not be accepted without specific order of Govt.",
      "The bidders intended to enjoy exemption from depositing EMD, should submit necessary govt. orders with NOC of ARCS.  In support of such exemption from depositing EMD at the time of e-filling.",
      "Conditional rate will not be entertained.",
      "All the pages of the agreement for the work executed should be signed by the participant/ Tenderer.",
      "Work order will be issued when fund is availale"
    ],
    qualidyceteria: [
      "Valid PAN issued by the IT Deptt. Govt. of India.",
      "Valid 15-digit Goods and Services Tax identification or registration Number (GSTIN) and up-to-date GST return under GST Act, 2017.",
      "Completion and payment Certificate of State/Central Govt., undertaking/Statutory Bodies and having 60% (Sixty percent) of the estimated amount put to tender.",
      "Work Order of the work(s), against which the Completion Certificate & Payment Certificate has been issued.",
      "Professional Tax Clearance Certificate and Upto date Challan.",
      "Valid up-to-date Trade License.",
      "Last Three financial years Income Tax Return Certificate.",
      "The scan copy of the participation charge and the Deposited challan of the EMD are to be uploaded in the appropriate folder with sign and work SI. No. should be mentioned clearly on the top of the deposited challan, as a Proof of participation charge and EMD.",
      "In case of Partnership Firm / Registered Company, the intending Tenderers are requested to submit the copy of the DEED of Partnership / the company shall furnish the Article of Association and Memorandum in support of proof or so."
    ],
    termcondition: [
      "All the Intending Tenderers must have to visit the work site to judge the local condition from all corners and no complain about the site will be entertained afterwards. It will be presumed that the agency offered the tender rate after review of entire position of the work site.",
      "This Notice Inviting Tender will be treated as a part of the Tender Document.",
      "In case of any day, meant for this tender, appears to be an unscheduled holiday, the next working day will be treated as scheduled / prescribed day for the same purpose.",
      "Agencies shall have to arrange required land for installation of plant & machineries, storing of materials, labour shed, laboratory etc. at their own cost and responsibility nearest to the work site if needed.",
      "No preconditioned tender will be accepted.",
      "All the rates of works are inclusive of all taxes, cess, levy, octroi, royalty, transportation, loading, unloading, stacking, etc including all other incidental charges therein.",
      "Bidder(s) may be asked to submit rate analysis for items where the quoted rates are above 10% less than the estimated amount put to tender. Such bids may also be considered as null and void if there is a reason to believe that the Bidders have formed a cartel and rates have been manipulated, unbalanced or unreasonable.",
      "The Successful Tenderer, herein, will have to execute an agreement on a Non-Judicial Stamp worth Rs. 10/- only and the work has to be started within 07(Seven) days from the issue of work order without fail before the work order is issued with the Gram Panchayat wherein the description, specification, quantity, date of completion of work, other mandatory conditions and ESMF (Environmental and Social Management Framework) issues shall be detailed. Failure to execute the contract will lead to automatic cancellation of the bid.",
      "The contractor responsible for the execution of the work as per accept the “Schedule of agreed rates” (insert the quoted L1 rates as in the Tender submitted by this bidder using the Standard Format) which shall be deemed to form and be read and construed as part of the Contract.",
      `Time & Cost over-run will not be permitted. In case of any work not being completed by the contractor within the stipulated time-frame, necessary Penal measure, in the tune of deduction of an amount, as decided by the ${gpnameinshort }Gram Panchayat Office, will be imposed.`,
      "Periodical tests on materials and works shall have to be conducted as per the relevant codes. The results of all quality control tests and observations should be required for getting any payment. Any claim regarding payment will not be entertained without quality control test report including the certificate of Engineers concerned.",
      "The contractor shall obey the forest protection rules and not be involved in cutting of trees at the work site, shall not be involved in destruction of archaeological importance, shall not encroach any type of land, will never cause conflict among community groups, shall never be involved in construction of roads on fertile agricultural land or encroaching on water bodies.",
      "Necessary deduction towards Income Tax ,Labour Welfare Cess and GST etc. will be made as per Govt. norms, and Security Deposit of total 10% (ten percent) of the value of work will be deducted from each progressive or Final bill as the case may be.",
      "No child labour to be engage under necessary child labour acts.",
      "Sub-allotment of work under any circumstances will not be permitted.",
      "Payment of Final bill/R.A bill of above mentioned work will be made after satisfactory verification of the total claim with reference to all related records and papers as per availability of fund &The Work done will be inspected and measured as per P & RD D/West Bengal PWD norms by the Nirman Sahayak /E.I.C and admissible payment will be determined on the basis of the schedule of agreed rates. No claim for delay in payment of bill will be entertained. At the time of payment of each bill deduction will be made as per present norms of Govt. of West Bengal.",
      "Incomplete, defective, erroneous/unsigned tender will be rejected without comparison.",
      "All the works to be executed according to drawing and specification approved by the authority and the direction of the Nirman Sahayak / Engineer-in-Charge is to be strictly followed.",
      "Before start of work the cutting of bushes, cleaning jungles etc for which no extra payment will be entertained.",
      "The successful/L1 bidder will claim his EMD after completion of work on his own letter head pad as a prayer along with work order and e-generating challan from Govt. of West Bengal, e-procurement GRIPS eChallan.",
      "Time is the essence of contract. The successful contractor must complete the work within the time Specified for completion. The permitted enlargement, extension, reduction, omissions, alterations or additions resulting out a formal duly signed amendment to the contract will not affect the validity or any other conditions of the contract except for those conditions that are explicitly specified in the formal duly signed amendment to the contract. If any contractor fails to complete the work within the stipulated time the work order issued in his favour will be cancelled without assigning any reason thereof. The undersigned may also proceed to get the balance work completed by any other means including through other contractors. The excess expenditure, if any, due to such a step would be recoverable from the unpaid bills/security deposit of the tenderer. This is apart from any other measure the undersigned may take, including blacklisting of the contractors or forfeited of earnest money or both of them.",
      "The concerned Nirman Sahayak/E.I.C nominated by the employer / PIA shall be entitled to make any alterations to the design, character, position, quantities, dimensions or method of execution thereof, and to order for any extra or additional works to be done, the contractor will not be entitled to any compensation for any reduction or omission, but will be eligible for payments only for the actual amount of work done and for the approved material furnished against a specific item in the schedule of work as per the specified rates.",
      `In the event of any of the provisions of the contract requiring amendment, the amendments shall be made in writing and shall be signed by the Pradhan, ${gpnameinshort} Gram Panchayat and the Contractor and no work as result of any amendment shall proceed without mutually agreed and signed amendment to that effect. Any verbal contracts / understandings relating to abandoning, modifying, extending, reducing or supplementing any part(s) of the contracted work will not be executed until they are incorporated as a formal duly signed amendment to the contract.`,
      "Acceptance of the lowest tender is not obligatory and the undersigned reserves the right to accept or reject any or all the tenders without assigning any reason whatsoever and also to split up the tendered work to more than one contractor in the interest of better scheme execution.",
      "The contractor will be responsible for any damages, accidents, mishaps, thefts at the work site during execution of the work and liabilities arising there from or any loss of materials, time monetary of pertaining to any life has to be entirely accounted as per norms by the Executing Farm / Agencies / Contractor.",
      "On account of any delay of the work, as per mention schedule time mention in the notice, penalty has to be paid by the agency / contractor/ firms. The amount of penalty under consideration as per order /norms/resolution.",
      "The final bill/Payment will be done as per work done measurement after availability of fund.",
      "The contractor will entirely be responsible for rectification of any defects during work within defect liabity period. The security deposit retained as per west Bengal Govt. Norms will be returned within 10 days of the successful expiry of the defect liability period & Blacklisting of the tenderer may be adopted if found necessary in case of non completion of work as per the Gram Panchayat resolution",
      "After the issuance of the work order and confirmation of fund availability, the selected bidder must collect the work order within 30 (thirty) days. Failure to do so will result in the cancellation of the awarded tender, and the second lowest bidder may be considered for award of the work as per tender norms.",
      "If the awarded work is not completed within the stipulated time frame, a late fee or penalty shall be imposed as per the Gram Panchayat resolution in force. This penalty will be strictly enforced and deducted from the final bill amount."
    ]
  }
];

export const tenderForwardedTo = [
  "The S.D.O., Balurghat Sub Division",
  `The B.D.O., ${blockname} Block`,
  "The DIO, NIC Balurghat, Dakshin Dinajpur",
  "The Librarian, Local rural library",
  "Sahaj Tathya Mitra Kendra, Local",
  `Opposition Leader, No-3 ${gpnameinshort} G.P.`,
  "Office Notice Board",
  "Office Copy"
];
