//       religion: "",
//       : "",
//       : "",
//       computerLiterate: "",
//       : "",
//       bloodGroup: "",
//       contactNo: "",
//       whatsappNo: "",
//       email: "",
//       address: "",
//       village: "",
//       pin: "",
//       postOffice: "",
//       district: "",
//       policeStation: "",
//       aadhar: "",
//       pan: "",
//       epic: "",
//       profession: "",
//       annualFamilyIncome: "",
//       photo: undefined,
//     }

export const MemberstepObject = [
  {
    id: 1,
    title: "Basic Information",
    fields: [
      "salutation",
      "firstName",
      "middleName",
      "lastName",
      "fatherGuardianName",
      "dob",
      "gender",
    ],
  },
  {
    id: 2,
    title: "Additional Information",
    fields: [
      "religion",
      "caste",
      "eduQualification",
      "computerLiterate",
      "motherTongue",
      "bloodGroup",
      "contactNo",
      "whatsappNo",
      "email",
    ],
  },
  {
    id: 3,
    title: "Residential Address",
    fields: [
      "address",
      "village",
      "pin",
      "postOffice",
      "district",
      "policeStation",
    ],
  },
  {
    id: 4,
    title: "Id & Professional & Photo",
    fields: [
      "aadhar",
      "pan",
      "epic",
      "profession",
      "annualFamilyIncome",
      "photo",
    ],
  },
];
