
import * as z from "zod"

export const populationSchema = z.object({
  household: z.coerce.number().int().default(0),
  male: z.coerce.number().int().default(0),
  female: z.coerce.number().int().default(0),
  ltmale: z.coerce.number().int().default(0),
  ltfemale: z.coerce.number().int().default(0),
  scmale: z.coerce.number().int().default(0),
  scfemale: z.coerce.number().int().default(0),
  stmale: z.coerce.number().int().default(0),
  stfemale: z.coerce.number().int().default(0),
  obcmale: z.coerce.number().int().default(0),
  obcfemale: z.coerce.number().int().default(0),
  childrenmale06: z.coerce.number().int().default(0),
  childrenfemale06: z.coerce.number().int().default(0),
})

export const educationSchema = z.object({
  totalStudents: z.coerce.number().int().default(0),
  maleStudents: z.coerce.number().int().default(0),
  femaleStudents: z.coerce.number().int().default(0),
  scStudents: z.coerce.number().int().default(0),
  stStudents: z.coerce.number().int().default(0),
  obcStudents: z.coerce.number().int().default(0),
  dropoutRate: z.coerce.number().default(0),
  maleDropoutRate: z.coerce.number().default(0),
  femaleDropoutRate: z.coerce.number().default(0),
  teacherCount: z.coerce.number().int().default(0),
  maleTeachers: z.coerce.number().int().default(0),
  femaleTeachers: z.coerce.number().int().default(0),
  trainedTeachers: z.coerce.number().int().default(0),
  midDayMealBeneficiaries: z.coerce.number().int().default(0),
  scholarshipBeneficiaries: z.coerce.number().int().default(0),
  digitalClassrooms: z.coerce.number().int().default(0),
  playgroundAvailable: z.boolean().default(false),
  libraryAvailable: z.boolean().default(false),
  computerLabAvailable: z.boolean().default(false),
})

export const infraSchema = z.object({
  anganwadi: z.coerce.number().int().default(0),
  icdsCentre: z.coerce.number().int().default(0),
  healthCentre: z.coerce.number().int().default(0),
  subCentre: z.coerce.number().int().default(0),
  primaryHealthCenter: z.coerce.number().int().default(0),
  communityHealthCenter: z.coerce.number().int().default(0),
  veterinaryHospital: z.coerce.number().int().default(0),
  postOffice: z.coerce.number().int().default(0),
  bankBranch: z.coerce.number().int().default(0),
  atmCenter: z.coerce.number().int().default(0),
  policeStation: z.coerce.number().int().default(0),
  policeOutpost: z.coerce.number().int().default(0),
  fireStation: z.coerce.number().int().default(0),
  busStand: z.coerce.number().int().default(0),
  railwayStation: z.coerce.number().int().default(0),
  marketComplex: z.coerce.number().int().default(0),
  fairPriceShop: z.coerce.number().int().default(0),
  cooperativeSociety: z.coerce.number().int().default(0),
  selfHelpGroups: z.coerce.number().int().default(0),
})

export const healthSchema = z.object({
  birthRate: z.coerce.number().default(0),
  deathRate: z.coerce.number().default(0),
  infantMortalityRate: z.coerce.number().default(0),
  maternalMortalityRate: z.coerce.number().default(0),
  immunizationCoverage: z.coerce.number().default(0),
  malnutritionRate: z.coerce.number().default(0),
  anemiaCases: z.coerce.number().int().default(0),
  tuberculosisCases: z.coerce.number().int().default(0),
  malariaIncidence: z.coerce.number().int().default(0),
  dengueIncidence: z.coerce.number().int().default(0),
  pregnantWomen: z.coerce.number().int().default(0),
  institutionalDeliveries: z.coerce.number().int().default(0),
  homeDeliveries: z.coerce.number().int().default(0),
  contraceptiveUsers: z.coerce.number().int().default(0),
  familyPlanningAdopters: z.coerce.number().int().default(0),
  healthInsuranceCoverage: z.coerce.number().int().default(0),
  ayushTreatmentSeekers: z.coerce.number().int().default(0),
})

export const sanitationSchema = z.object({
  householdsWithToilets: z.coerce.number().int().default(0),
  householdsUsingToilets: z.coerce.number().int().default(0),
  publicToiletFacilities: z.coerce.number().int().default(0),
  communityToilets: z.coerce.number().int().default(0),
  schoolToilets: z.coerce.number().int().default(0),
  anganwadiToilets: z.coerce.number().int().default(0),
  solidWasteManagement: z.boolean().default(false),
  liquidWasteManagement: z.boolean().default(false),
  wasteSegregationPractice: z.boolean().default(false),
  compostPits: z.coerce.number().int().default(0),
  bioGasPlants: z.coerce.number().int().default(0),
  drainageSystem: z.boolean().default(false),
  openDefecationFree: z.boolean().default(false),
  swachhBharatMissionStatus: z.string().nullable().default(""), // Changed to nullable
})

export const waterSchema = z.object({
  pipedWaterConnections: z.coerce.number().int().default(0),
  handPumps: z.coerce.number().int().default(0),
  tubewells: z.coerce.number().int().default(0),
  openWells: z.coerce.number().int().default(0),
  borewells: z.coerce.number().int().default(0),
  waterTankers: z.coerce.number().int().default(0),
  waterSourcesTested: z.coerce.number().int().default(0),
  safeWaterSources: z.coerce.number().int().default(0),
  unsafeWaterSources: z.coerce.number().int().default(0),
  waterQualityTested: z.boolean().default(false),
  fluorideContamination: z.boolean().default(false),
  arsenicContamination: z.boolean().default(false),
  ironContamination: z.boolean().default(false),
  waterTreatmentPlant: z.boolean().default(false),
  rainwaterHarvesting: z.coerce.number().int().default(0),
  waterConservationStructures: z.coerce.number().int().default(0),
  jjmCoverage: z.coerce.number().default(0),
})

export const economicSchema = z.object({
  totalWorkers: z.coerce.number().int().default(0),
  mainWorkers: z.coerce.number().int().default(0),
  marginalWorkers: z.coerce.number().int().default(0),
  nonWorkers: z.coerce.number().int().default(0),
  cultivators: z.coerce.number().int().default(0),
  agriculturalLabourers: z.coerce.number().int().default(0),
  householdIndustryWorkers: z.coerce.number().int().default(0),
  otherWorkers: z.coerce.number().int().default(0),
  unemploymentRate: z.coerce.number().default(0),
  femaleWorkParticipation: z.coerce.number().default(0),
  averageIncome: z.coerce.number().default(0),
  belowPovertyLine: z.coerce.number().int().default(0),
  bankAccountHolders: z.coerce.number().int().default(0),
  kccHolders: z.coerce.number().int().default(0), // Kisan Credit Card
  pmKisanBeneficiaries: z.coerce.number().int().default(0),
  mgnregaJobCards: z.coerce.number().int().default(0),
  mgnregaWorkDays: z.coerce.number().int().default(0),
  skillDevelopmentTrainees: z.coerce.number().int().default(0),
  entrepreneurshipPrograms: z.coerce.number().int().default(0),
})

export const eduInstitutionSchema = z.object({
 
  ssk: z.coerce.number().int().default(0), // Shishu Shiksha Kendra
  anganwadi: z.coerce.number().int().default(0),
  primarySchool: z.coerce.number().int().default(0),
  upperPrimary: z.coerce.number().int().default(0),
  highSchool: z.coerce.number().int().default(0),
  higherSecondary: z.coerce.number().int().default(0),
  madrasah: z.coerce.number().int().default(0),
  juniorHigh: z.coerce.number().int().default(0),
  college: z.coerce.number().int().default(0),
  university: z.coerce.number().int().default(0),
  technicalInstitute: z.coerce.number().int().default(0),
  vocationalCenter: z.coerce.number().int().default(0),
  adultEducationCenter: z.coerce.number().int().default(0),
  libraryCount: z.coerce.number().int().default(0),
  computerCenter: z.coerce.number().int().default(0),
})

export const formSchema = z.object({
  lgdcode: z.coerce.number().int(),
  jlno: z.coerce.number().int(),
  name: z.string(),
  year: z.string(),
  population: populationSchema.optional(),
  education: educationSchema.optional(),
  infrastructure: infraSchema.optional(),
  health: healthSchema.optional(),
  sanitation: sanitationSchema.optional(),
  water: waterSchema.optional(),
  economic: economicSchema.optional(),
  eduInstitution: eduInstitutionSchema.optional(),
})
